services:
  - type: web
    name: jaguar-market
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_simple:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /
    autoDeploy: true
